# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1my68TKBr0-g7nNCT7dUW51Ex06e2boIm
"""

new_str = str(input())
cx = new_str.count('x')
cy = new_str.count('y')
print(f'x: {cx}, y: {cy}.')