# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1my68TKBr0-g7nNCT7dUW51Ex06e2boIm
"""

#при условии, что скобки не пересекаются и их две
new_str = str(input())
index_otkr = 1 + new_str.find('(')
index_zakr = new_str.find(')')
index_otkr2 = 1 + new_str.rfind('(')
index_zakr2 = new_str.rfind(')')
vskob = new_str[index_otkr:index_zakr]
vskob2 = new_str[index_otkr2:index_zakr2]
print(vskob)
print(vskob2)